[tool.poetry]
name = "hyper-resource-sanic"
version = "0.1.0"
description = ""
authors = ["RogerioBorba <rogerio.borba17@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
sanic = "^20.6.3"
secure = "^0.2.1"
sanic-envconfig = "^1.3.3"
databases = {extras = ["postgresql"], version = "^0.3.2"}
sanic-openapi = "^0.6.2"
sqlacodegen = "^2.3.0"
environs = "^8.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
