from sqlalchemy import types

print(len(types.__all__))

def python_to_sqlalchemy_type(python_type: type) -> str:
    d = {
        # "TypeEngine",
        # "TypeDecorator",
        # "UserDefinedType",
        # "INT",
        # "CHAR",
        str: "VARCHAR",
        # "NCHAR",
        # "NVARCHAR",
        # "TEXT",
        # "Text",
        float: "FLOAT",
        # "NUMERIC",
        # "REAL",
        # "DECIMAL",
        # "TIMESTAMP",
        # "DATETIME",
        # "CLOB",
        # "BLOB",
        # "BINARY",
        # "VARBINARY",
        bool: "BOOLEAN",
        # "BIGINT",
        # "SMALLINT",
        int: "INTEGER",
        # "DATE",
        # "TIME",
        # "String",
        # "Integer",
        # "SmallInteger",
        # "BigInteger",
        # "Numeric",
        # "Float",
        # "DateTime",
        # "Date",
        # "Time",
        # "LargeBinary",
        # "Binary",
        # "Boolean",
        # "Unicode",
        # "Concatenable",
        # "UnicodeText",
        # "PickleType",
        # "Interval",
        # "Enum",
        # "Indexable",
        list: "ARRAY",
        # "JSON",
    }
    return d[python_type]